project:
  type: website
  output-dir: docs

website:
  title: "Anja Shahu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: 20241025_resume.pdf
        text: Resume

format:
  html:
    theme: 
      light: minty
      dark: vapor
    css: styles.css
    toc: true

editor: visual

